"""initial

Revision ID: 22b1ee8ff1f4
Revises: 
Create Date: 2026-05-08 21:33:37.305043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_root', sa.String(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.CheckConstraint('id = 1', name='catalog_meta_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samples',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('data_source', sa.Enum('cryoet', 'simulation', name='datasource'), nullable=False),
    sa.Column('project', sa.Enum('chromatin', 'synapse', name='project'), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('cell_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('scans',
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=False),
    sa.Column('ended_at', sa.Float(), nullable=True),
    sa.Column('root', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('samples_upserted', sa.Integer(), nullable=True),
    sa.Column('samples_skipped', sa.Integer(), nullable=True),
    sa.Column('samples_failed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('scan_run_id')
    )
    op.create_table('acquisitions',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('tilt_spacing', sa.Float(), nullable=True),
    sa.Column('defocus_range', sa.String(), nullable=True),
    sa.Column('energy_filter', sa.String(), nullable=True),
    sa.Column('phase_plate', sa.Boolean(), nullable=True),
    sa.Column('microscope', sa.String(), nullable=True),
    sa.Column('pixel_size', sa.Float(), nullable=True),
    sa.Column('dose_per_tilt', sa.JSON(), nullable=True),
    sa.Column('total_dose', sa.Float(), nullable=True),
    sa.Column('tilt_min', sa.Float(), nullable=True),
    sa.Column('tilt_max', sa.Float(), nullable=True),
    sa.Column('tilt_axis', sa.Float(), nullable=True),
    sa.Column('defocus_per_image', sa.JSON(), nullable=True),
    sa.Column('date_collected', sa.Date(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('energy_filter_slit_width', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('camera', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id')
    )
    op.create_table('aunp',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('size_nm', sa.Float(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('fluorophore', sa.String(), nullable=True),
    sa.Column('concentration_value', sa.Float(), nullable=True),
    sa.Column('concentration_unit', sa.String(), nullable=True),
    sa.Column('conjugation', sa.String(), nullable=True),
    sa.Column('conjugation_target', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'ordinal')
    )
    op.create_table('chromatin',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('substrate', sa.String(), nullable=True),
    sa.Column('linker_length_bp', sa.Float(), nullable=True),
    sa.Column('linker_pattern', sa.JSON(), nullable=True),
    sa.Column('linker_distribution', sa.String(), nullable=True),
    sa.Column('buffer', sa.String(), nullable=True),
    sa.Column('ptm', sa.String(), nullable=True),
    sa.Column('histone_variants', sa.String(), nullable=True),
    sa.Column('transcription_factors', sa.String(), nullable=True),
    sa.Column('nucleosome_count', sa.Integer(), nullable=True),
    sa.Column('dna_length_bp', sa.Integer(), nullable=True),
    sa.Column('nucleosome_uM', sa.Float(), nullable=True),
    sa.Column('sequence_identity', sa.String(), nullable=True),
    sa.Column('nucleosome_footprint', sa.JSON(), nullable=True),
    sa.Column('linker_length_fraction', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('extras',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_pk_json', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('entity_type', 'entity_pk_json', 'key')
    )
    with op.batch_alter_table('extras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extras_sample_id'), ['sample_id'], unique=False)

    op.create_table('freezing',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('grid_type', sa.String(), nullable=True),
    sa.Column('cryoprotectant', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('planchette_size', sa.String(), nullable=True),
    sa.Column('spacer_thickness', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('milling',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('scheme', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('scan_state',
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('last_scanned', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('path')
    )
    with op.batch_alter_table('scan_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_state_sample_id'), ['sample_id'], unique=False)

    op.create_table('scan_warnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('detected_at', sa.Float(), nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scans.scan_run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_warnings_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_warnings_scan_run_id'), ['scan_run_id'], unique=False)

    op.create_table('simulation',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('synapse',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('label_target', sa.String(), nullable=True),
    sa.Column('label_strategy', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.sample_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('annotations',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('annotation_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('target_tomogram', sa.String(length=128), nullable=True),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id', 'acquisition_id'], ['acquisitions.sample_id', 'acquisitions.acquisition_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id', 'annotation_id')
    )
    op.create_table('tomograms',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('tomogram_id', sa.String(length=128), nullable=False),
    sa.Column('pipeline', sa.String(), nullable=True),
    sa.Column('software', sa.String(), nullable=True),
    sa.Column('voxel_bin', sa.Integer(), nullable=True),
    sa.Column('derived_from', sa.JSON(), nullable=False),
    sa.Column('is_raw', sa.Boolean(), nullable=True),
    sa.Column('image_size_x', sa.Integer(), nullable=True),
    sa.Column('image_size_y', sa.Integer(), nullable=True),
    sa.Column('image_size_z', sa.Integer(), nullable=True),
    sa.Column('mrc_path', sa.String(), nullable=True),
    sa.Column('zarr_path', sa.String(), nullable=True),
    sa.Column('zarr_axes', sa.String(), nullable=True),
    sa.Column('zarr_scale', sa.JSON(), nullable=True),
    sa.Column('voxel_spacing_angstrom', sa.Float(), nullable=True),
    sa.Column('voxel_spacing_angstrom_implied', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id', 'acquisition_id'], ['acquisitions.sample_id', 'acquisitions.acquisition_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id', 'tomogram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tomograms')
    op.drop_table('annotations')
    op.drop_table('synapse')
    op.drop_table('simulation')
    with op.batch_alter_table('scan_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_warnings_scan_run_id'))
        batch_op.drop_index(batch_op.f('ix_scan_warnings_sample_id'))

    op.drop_table('scan_warnings')
    with op.batch_alter_table('scan_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_state_sample_id'))

    op.drop_table('scan_state')
    op.drop_table('milling')
    op.drop_table('freezing')
    with op.batch_alter_table('extras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extras_sample_id'))

    op.drop_table('extras')
    op.drop_table('chromatin')
    op.drop_table('aunp')
    op.drop_table('acquisitions')
    op.drop_table('scans')
    op.drop_table('samples')
    op.drop_table('catalog_meta')
    # ### end Alembic commands ###
