"""dashboard_mvp

Revision ID: bf28fba453a6
Revises: 0001
Create Date: 2026-05-08 21:36:19.001486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf28fba453a6"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tilt_series',
    sa.Column('sample_id', sa.String(length=128), nullable=False),
    sa.Column('acquisition_id', sa.String(length=128), nullable=False),
    sa.Column('tilt_series_id', sa.String(length=128), nullable=False),
    sa.Column('mdoc_path', sa.String(), nullable=True),
    sa.Column('st_path', sa.String(), nullable=True),
    sa.Column('zarr_path', sa.String(), nullable=True),
    sa.Column('n_tilts', sa.Integer(), nullable=True),
    sa.Column('tilt_range_min', sa.Float(), nullable=True),
    sa.Column('tilt_range_max', sa.Float(), nullable=True),
    sa.Column('tilt_axis_angle', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('pixel_spacing', sa.Float(), nullable=True),
    sa.Column('image_format', sa.String(), nullable=True),
    sa.Column('microscope', sa.String(), nullable=True),
    sa.Column('camera', sa.String(), nullable=True),
    sa.Column('tilt_angles', sa.JSON(), nullable=True),
    sa.Column('mtime', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id', 'acquisition_id'], ['acquisitions.sample_id', 'acquisitions.acquisition_id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'acquisition_id', 'tilt_series_id')
    )
    with op.batch_alter_table('acquisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))

    with op.batch_alter_table('tomograms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_bytes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tomograms', schema=None) as batch_op:
        batch_op.drop_column('size_bytes')

    with op.batch_alter_table('acquisitions', schema=None) as batch_op:
        batch_op.drop_column('path')

    op.drop_table('tilt_series')
    # ### end Alembic commands ###
