/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MdSimulationRouteImport } from './routes/md-simulation'
import { Route as ExperimentalRouteImport } from './routes/experimental'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as SamplesSampleIdRouteImport } from './routes/samples.$sampleId'
import { Route as ManageScansRouteImport } from './routes/manage.scans'
import { Route as AcquisitionsAcquisitionIdRouteImport } from './routes/acquisitions.$acquisitionId'
import { Route as ManageScansScanIdRouteImport } from './routes/manage.scans_.$scanId'

const MdSimulationRoute = MdSimulationRouteImport.update({
  id: '/md-simulation',
  path: '/md-simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentalRoute = ExperimentalRouteImport.update({
  id: '/experimental',
  path: '/experimental',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesSampleIdRoute = SamplesSampleIdRouteImport.update({
  id: '/samples/$sampleId',
  path: '/samples/$sampleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageScansRoute = ManageScansRouteImport.update({
  id: '/manage/scans',
  path: '/manage/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsAcquisitionIdRoute =
  AcquisitionsAcquisitionIdRouteImport.update({
    id: '/acquisitions/$acquisitionId',
    path: '/acquisitions/$acquisitionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageScansScanIdRoute = ManageScansScanIdRouteImport.update({
  id: '/manage/scans_/$scanId',
  path: '/manage/scans/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experimental': typeof ExperimentalRoute
  '/md-simulation': typeof MdSimulationRoute
  '/acquisitions/$acquisitionId': typeof AcquisitionsAcquisitionIdRoute
  '/manage/scans': typeof ManageScansRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/manage/': typeof ManageIndexRoute
  '/manage/scans/$scanId': typeof ManageScansScanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experimental': typeof ExperimentalRoute
  '/md-simulation': typeof MdSimulationRoute
  '/acquisitions/$acquisitionId': typeof AcquisitionsAcquisitionIdRoute
  '/manage/scans': typeof ManageScansRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/manage': typeof ManageIndexRoute
  '/manage/scans/$scanId': typeof ManageScansScanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experimental': typeof ExperimentalRoute
  '/md-simulation': typeof MdSimulationRoute
  '/acquisitions/$acquisitionId': typeof AcquisitionsAcquisitionIdRoute
  '/manage/scans': typeof ManageScansRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/manage/': typeof ManageIndexRoute
  '/manage/scans_/$scanId': typeof ManageScansScanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experimental'
    | '/md-simulation'
    | '/acquisitions/$acquisitionId'
    | '/manage/scans'
    | '/samples/$sampleId'
    | '/manage/'
    | '/manage/scans/$scanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experimental'
    | '/md-simulation'
    | '/acquisitions/$acquisitionId'
    | '/manage/scans'
    | '/samples/$sampleId'
    | '/manage'
    | '/manage/scans/$scanId'
  id:
    | '__root__'
    | '/'
    | '/experimental'
    | '/md-simulation'
    | '/acquisitions/$acquisitionId'
    | '/manage/scans'
    | '/samples/$sampleId'
    | '/manage/'
    | '/manage/scans_/$scanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperimentalRoute: typeof ExperimentalRoute
  MdSimulationRoute: typeof MdSimulationRoute
  AcquisitionsAcquisitionIdRoute: typeof AcquisitionsAcquisitionIdRoute
  ManageScansRoute: typeof ManageScansRoute
  SamplesSampleIdRoute: typeof SamplesSampleIdRoute
  ManageIndexRoute: typeof ManageIndexRoute
  ManageScansScanIdRoute: typeof ManageScansScanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/md-simulation': {
      id: '/md-simulation'
      path: '/md-simulation'
      fullPath: '/md-simulation'
      preLoaderRoute: typeof MdSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experimental': {
      id: '/experimental'
      path: '/experimental'
      fullPath: '/experimental'
      preLoaderRoute: typeof ExperimentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$sampleId': {
      id: '/samples/$sampleId'
      path: '/samples/$sampleId'
      fullPath: '/samples/$sampleId'
      preLoaderRoute: typeof SamplesSampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/scans': {
      id: '/manage/scans'
      path: '/manage/scans'
      fullPath: '/manage/scans'
      preLoaderRoute: typeof ManageScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions/$acquisitionId': {
      id: '/acquisitions/$acquisitionId'
      path: '/acquisitions/$acquisitionId'
      fullPath: '/acquisitions/$acquisitionId'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/scans_/$scanId': {
      id: '/manage/scans_/$scanId'
      path: '/manage/scans/$scanId'
      fullPath: '/manage/scans/$scanId'
      preLoaderRoute: typeof ManageScansScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperimentalRoute: ExperimentalRoute,
  MdSimulationRoute: MdSimulationRoute,
  AcquisitionsAcquisitionIdRoute: AcquisitionsAcquisitionIdRoute,
  ManageScansRoute: ManageScansRoute,
  SamplesSampleIdRoute: SamplesSampleIdRoute,
  ManageIndexRoute: ManageIndexRoute,
  ManageScansScanIdRoute: ManageScansScanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
